spring:
  application:
    name: gulimall-auth-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  redis:
    host: 127.0.0.1
    port: 6379
    password: 123


#  thymeleaf:
#    cache: false

#server:
logging:
  level:
    com.gulimall.gulimallauthserver: debug
#  port: 20000