spring:
  application:
    name: gulimall-seckill
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

    sentinel:
      transport:
        dashboard: localhost:8333
        port: 8719

  thymeleaf:
    cache: false

  redis:
    host: 127.0.0.1
    port: 6379
    password: 123
  cache:
    type: redis # 明确指定使用redis作为缓存实现
    redis:
      time-to-live: 600000 # 缓存 ttl，单位毫秒
#      key-prefix: CACHE_ # 设置缓存 key 前缀
      use-key-prefix: true # 是否开启前缀
      cache-null-values: true # 是否缓存空值
      null-value-ttl: 2m # null 占位 TTL

  session:
    store-type: redis
    timeout: 30m

  rabbitmq:
    host: 127.0.0.1 # 虚拟机IP
    port: 5672 # 端口
    virtual-host: / # 虚拟主机
    username: admin # 用户名
    password: admin # 密码
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true # 只要抵达队列，以异步发送优先回调抵达确认
    listener:
      simple:
        acknowledge-mode: manual # 手动 ack 消息

  zipkin:
    base-url: http://localhost:9411 # Zipkin 服务器的地址
    discovery-client-enabled: false # 关闭服务发现，否则 springCloud 会把 zipkin 的 url 当作服务名称注册到配置的 nacos 中
    sender:
      type: web # 数据发送的方式：ACTIVEMQ RABBIT KAFKA WEB
  sleuth:
    sampler:
      probability: 1.0 # 采样率，1.0代表100%采样，生产环境可调低（如0.1）以减少性能开销


feign:
  client:
    config:
      default:
        connectTimeout: 5000 # 连接超时时间，单位毫秒
        readTimeout: 60000 # 读取超时时间，单位毫秒

  sentinel:
    enabled: true

server:
  port: 25000

management:
  endpoints:
    web:
      exposure:
        include: "*"