spring:
  application:
    name: gulimall-cart
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  thymeleaf:
    cache: false

  redis:
    host: 127.0.0.1
    port: 6379
    password: 123

  session:
    store-type: redis
    timeout: 30m

gulimall:
  thread:
    core-pool-size: 20
    max-pool-size: 200
    keep-alive-time: 10


#server:
logging:
  level:
    com.project.gulimall.cart: debug
#  port: 10000